global using mark.davison.finance.common.Entities;
global using mark.davison.finance.common.server;
global using mark.davison.finance.common.server.Identification;
global using mark.davison.finance.models.Entities;
global using mark.davison.finance.persistence.EntityDefaulter;
global using mark.davison.finance.persistence.Repository;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore.Metadata.Builders;
global using Microsoft.Extensions.Logging;
