global using mark.davison.common.client.abstractions.Authentication;
global using mark.davison.common.client.Authentication;
global using mark.davison.common.client.Ignition;
global using mark.davison.finance.web.components.Ignition;
global using mark.davison.finance.web.features;
global using mark.davison.finance.web.ui;
global using mark.davison.finance.web.ui.Ignition;
global using Microsoft.AspNetCore.Components.Web;
global using Microsoft.AspNetCore.Components.WebAssembly.Hosting;
