apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: zeno-finance-external-secret
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: zeno-finance-secret
  data:
  - secretKey: REDIS_PASSWORD
    remoteRef:
      key: kv/prod/redis
      property: PASSWORD
  - secretKey: CLIENT_SECRET
    remoteRef:
      key: kv/prod/finance
      property: CLIENT_SECRET
  - secretKey: SESSION_SECRET
    remoteRef:
      key: kv/prod/finance
      property: SESSION_SECRET
  - secretKey: DB_USERNAME
    remoteRef:
      key: kv/prod/finance
      property: DB_USERNAME
  - secretKey: DB_PASSWORD
    remoteRef:
      key: kv/prod/finance
      property: DB_PASSWORD