apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: zeno-finance-secret
spec:
  backendType: vault
  vaultMountPoint: zeno-cluster
  vaultRole: zeno-cluster-role
  kvVersion: 2
  data:
    - key: kv/data/zeno-cluster/finance/api
      property: CLIENT_SECRET
      name: CLIENT_SECRET
    - key: kv/data/zeno-cluster/finance/bff
      property: SESSION_SECRET
      name: SESSION_SECRET
    - key: kv/data/zeno-cluster/finance/redis
      property: password
      name: REDIS_PASSWORD
    - key: kv/data/zeno-cluster/finance/db
      property: username
      name: DB_USERNAME
    - key: kv/data/zeno-cluster/finance/db
      property: password
      name: DB_PASSWORD
    