apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: zeno-finance-external-secret
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: zeno-finance-secret
  data:
  - secretKey: REDIS_PASSWORD
    remoteRef:
      key: kv/redis
      property: password
  - secretKey: SESSION_SECRET
    remoteRef:
      key: kv/zeno/finance/app
      property: SESSION_SECRET
  - secretKey: CLIENT_SECRET
    remoteRef:
      key: kv/zeno/finance/app
      property: CLIENT_SECRET
  - secretKey: DB_USER
    remoteRef:
      key: kv/zeno/finance/api
      property: DB_USER
  - secretKey: DB_PASSWORD
    remoteRef:
      key: kv/zeno/finance/api
      property: DB_PASSWORD
  - secretKey: DB_NAME
    remoteRef:
      key: kv/zeno/finance/api
      property: DB_NAME