apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: zeno-finance-external-secret
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: zeno-finance-secret
  data:
  - secretKey: REDIS_PASSWORD
    remoteRef:
      key: kv/prod/redis
      property: PASSWORD