global:
  ingress:
    hostname: prod-ingress.markdavison.kiwi
    certIssuer: letsencrypt-staging
    proxyBufferSize: 64k
api:
  app: zeno-finance-api
  replicas: 1
  name: zeno-finance-api
  image: ghcr.io/markrdavison/markdavison-finance-api
  tag: v0.1.3
  port: 50000
  ingress:
    host: finance-api.markdavison.kiwi
  env:
    secret:
      - AUTH__CLIENT_SECRET
      - DATABASE__DB_USERNAME
      - DATABASE__DB_PASSWORD
      - REDIS__PASSWORD
    public:
      FINANCE__AUTH__CLIENT_ID: zeno-finance
      FINANCE__AUTH__AUDIENCE: zeno-finance
      FINANCE__AUTH__SESSION_NAME: zeno-finance-prod-session
      FINANCE__AUTH__SCOPE: openid profile email offline_access zeno-finance
      FINANCE__AUTH__AUTHORITY: https://keycloak.markdavison.kiwi/auth/realms/markdavison.kiwi
      FINANCE__CLAIMS__OIDC_ID_ATTRIBUTE: http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier
      FINANCE__CLAIMS__OIDC_EMAIL_ATTRIBUTE: http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress
      FINANCE__CLAIMS__OIDC_FIRST_NAME_ATTRIBUTE: http://schemas.xmlsoap.org/ws/2005/05/identity/claims/givenname
      FINANCE__CLAIMS__OIDC_LAST_NAME_ATTRIBUTE: http://schemas.xmlsoap.org/ws/2005/05/identity/claims/surname
      FINANCE__CLAIMS__OIDC_USERNAME_ATTRIBUTE: preferred_username
      FINANCE__REDIS__HOST: redis.markdavison.kiwi
      FINANCE__DATABASE__DATABASE_TYPE: postgres
      FINANCE__DATABASE__DB_DATABASE: prod-finance
      FINANCE__DATABASE__DB_PORT: 5432
      FINANCE__DATABASE__DB_HOST: postgres.markdavison.kiwi
      FINANCE__PRODUCTION_MODE: true
      FINANCE__URL: http://0.0.0.0:50000
bff:
  app: zeno-finance-bff
  replicas: 1
  name: zeno-finance-bff
  image: ghcr.io/markrdavison/markdavison-finance-bff
  tag: v0.1.3
  port: 40000
  ingress:
    host: finance-bff.markdavison.kiwi
  env:
    secret:
      - AUTH__CLIENT_SECRET
      - AUTH__SESSION_SECRET
      - REDIS__PASSWORD
    public:
      FINANCE__AUTH__AUTHORITY: https://keycloak.markdavison.kiwi/auth/realms/markdavison.kiwi
      FINANCE__AUTH__CLIENT_ID: zeno-finance
      FINANCE__AUTH__AUDIENCE: zeno-finance
      FINANCE__AUTH__SESSION_NAME: zeno-finance-prod-session
      FINANCE__AUTH__SCOPE: openid profile email offline_access zeno-finance
      FINANCE__CLAIMS__OIDC_ID_ATTRIBUTE: http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier
      FINANCE__CLAIMS__OIDC_EMAIL_ATTRIBUTE: http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress
      FINANCE__CLAIMS__OIDC_FIRST_NAME_ATTRIBUTE: http://schemas.xmlsoap.org/ws/2005/05/identity/claims/givenname
      FINANCE__CLAIMS__OIDC_LAST_NAME_ATTRIBUTE: http://schemas.xmlsoap.org/ws/2005/05/identity/claims/surname
      FINANCE__CLAIMS__OIDC_USERNAME_ATTRIBUTE: preferred_username
      FINANCE__REDIS__HOST: redis.markdavison.kiwi
      FINANCE__WEB_ORIGIN: https://finance.markdavison.kiwi
      FINANCE__BFF_ORIGIN: https://finance-bff.markdavison.kiwi
      FINANCE__API_ORIGIN: https://finance-api.markdavison.kiwi
      FINANCE__URL: http://0.0.0.0:40000
      FINANCE__PRODUCTION_MODE: true
web:
  app: zeno-finance-web
  replicas: 1
  name: zeno-finance-web
  image: ghcr.io/markrdavison/markdavison-finance-web
  tag: v0.1.3
  port: 80
  ingress:
    host: finance.markdavison.kiwi
  env:
    secret: []
    public:
      WEB_PORT: '80'
      FINANCE_BFF_BASE_URI: https://finance-bff.markdavison.kiwi
