global using mark.davison.common.client.abstractions.CQRS;
global using mark.davison.common.client.abstractions.Repository;
global using mark.davison.common.client.abstractions.State;
global using mark.davison.common.CQRS;
global using mark.davison.finance.bff.commands.Scenarios.CreateTransaction.Common;
global using mark.davison.finance.models.dtos.Queries.AccountListQuery;
global using mark.davison.finance.models.dtos.Queries.StartupQuery;
global using mark.davison.finance.models.dtos.Queries.TransactionByAccountQuery;
global using mark.davison.finance.models.dtos.Shared;
