name: publish

on:
  release:
    types: [published]

jobs:
  build-and-push-image-api:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4      
        
      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.MRD_GITHUB_PAT }}

      - name: Build and push Docker image
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          file: ./src/api.Dockerfile
          context: ./src
          push: true
          tags: |
            ghcr.io/markrdavison/markdavison-finance-api:latest
            ghcr.io/markrdavison/markdavison-finance-api:${{ github.event.release.tag_name }}
            

  build-and-push-image-bff:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4      
        
      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.MRD_GITHUB_PAT }}
          
      - name: Build and push Docker image
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          file: ./src/bff.Dockerfile
          context: ./src
          push: true
          tags: |
            ghcr.io/markrdavison/markdavison-finance-bff:latest
            ghcr.io/markrdavison/markdavison-finance-bff:${{ github.event.release.tag_name }}

  build-and-push-image-web:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4      
        
      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.MRD_GITHUB_PAT }}
          
      - name: Build and push Docker image
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          file: ./src/web.Dockerfile
          context: ./src
          push: true
          tags: |
            ghcr.io/markrdavison/markdavison-finance-web:latest
            ghcr.io/markrdavison/markdavison-finance-web:${{ github.event.release.tag_name }}

  update-gitops:
    needs: [build-and-push-image-api, build-and-push-image-bff, build-and-push-image-web]
    
    runs-on: ubuntu-latest
    
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4    
        with:
          submodules: true
          
      - name: install python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' 

      - name: update values        
        run: |
          python ./cicd/Helm/replaceYamlValue.py --file ./charts/values.tml --name api.tag --value ${{ github.event.release.tag_name }}
          python ./cicd/Helm/replaceYamlValue.py --file ./charts/values.tml --name api.tag --value ${{ github.event.release.tag_name }}
          python ./cicd/Helm/replaceYamlValue.py --file ./charts/values.tml --name api.tag --value ${{ github.event.release.tag_name }}- 
          git status

      # Commit all changed files back to the repository
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Updating git ops [skip ci]